atisNalchik=ATIS:New(AIRBASE.Caucasus.Nalchik, 264.950)
atisNalchik:SetRadioRelayUnitName("ATIS Nalchik")
atisNalchik:SetTowerFrequencies({132.100, 264.900})
atisNalchik:SetImperialUnits()
atisNalchik:Start()
