atisSukhumiBabushara=ATIS:New(AIRBASE.Caucasus.Sukhumi_Babushara, 275.850)
atisSukhumiBabushara:SetRadioRelayUnitName("ATIS SukhumiBabushara")
atisSukhumiBabushara:SetImperialUnits()
atisSukhumiBabushara:SetTowerFrequencies({258.200, 129.200})
atisSukhumiBabushara:Start()
