atisKutaisi=ATIS:New(AIRBASE.Caucasus.Kutaisi, 270.650)
atisKutaisi:SetRadioRelayUnitName("ATIS Kutaisi")
atisKutaisi:SetTowerFrequencies({264.100, 134.100})
atisKutaisi:SetImperialUnits()
atisKutaisi:SetTACAN(44)
atisKutaisi:Start()
