atisSenakiKolkhi=ATIS:New(AIRBASE.Caucasus.Senaki_Kolkhi, 251.150)
atisSenakiKolkhi:SetRadioRelayUnitName("ATIS SenakiKolkhi")
atisSenakiKolkhi:SetTowerFrequencies({261.100, 132.100})
atisSenakiKolkhi:SetImperialUnits()
atisSenakiKolkhi:SetTACAN(31)
atisSenakiKolkhi:Start()
