atisBatumi=ATIS:New(AIRBASE.Caucasus.Batumi, 245.650)
atisBatumi:SetRadioRelayUnitName("ATIS Batumi")
atisBatumi:SetTowerFrequencies({260.100, 131.100})
atisBatumi:SetImperialUnits()
atisBatumi:SetTACAN(16)
atisBatumi:Start()
