AWNavyBoys = AIRWING:New("GeorgeWashington","NavyBoys")
AWNavyBoys:SetMarker(false)
AWNavyBoys:SetAirbase(AIRBASE:FindByName("GeorgeWashington"))
AWNavyBoys:SetRespawnAfterDestroyed(900)
AWNavyBoys:SetTakeoffCold()
AWNavyBoys:__Start(2)

AWIncirlik = AIRWING:New("Incirlik","Airwing Incirlik")
AWIncirlik:SetMarker(false)
AWIncirlik:SetAirbase(AIRBASE:FindByName(AIRBASE.Syria.Incirlik))
AWIncirlik:SetRespawnAfterDestroyed(900)
AWIncirlik:SetTakeoffCold()
AWIncirlik:__Start(2)

AwAfacs = AIRWING:New("Incirlik","Airwing Incirlik AFACs")
AwAfacs:SetMarker(false)
AwAfacs:SetAirbase(AIRBASE:FindByName(AIRBASE.Syria.Incirlik))
AwAfacs:SetRespawnAfterDestroyed(900)
AwAfacs:SetTakeoffCold()
AwAfacs:__Start(2)

AwRotary = AIRWING:New("FarpResupplyLager","Airwing Helo Supply1")
AwRotary:SetMarker(false)
AwRotary:SetAirbase(AIRBASE:FindByName("FarpResupply"))
AwRotary:SetRespawnAfterDestroyed(900)
AwRotary:SetTakeoffCold()
AwRotary:__Start(2)

local squadronTransportHelo1 = SQUADRON:New("FrpSplyHelo", 8, "FrpSplyHelo") --Ops.Squadron#SQUADRON
squadronTransportHelo1:SetSkill(AI.Skill.HIGH)
squadronTransportHelo1:AddMissionCapability({AUFTRAG.Type.ORBIT, AUFTRAG.Type.HOVER},100)
AwRotary:AddSquadron(squadronTransportHelo1)
AwRotary:NewPayload("FrpSplyHelo",-1,{AUFTRAG.Type.ORBIT, AUFTRAG.Type.HOVER},100)

local squadAFACs = SQUADRON:New("AFAC Incirlik_Reaper", 8, "AFAC Incirlik_Reaper") --Ops.Squadron#SQUADRON
squadAFACs:SetSkill(AI.Skill.HIGH)
squadAFACs:AddMissionCapability({AUFTRAG.Type.ORBIT},100)
AwAfacs:AddSquadron(squadAFACs)
AwAfacs:NewPayload("AFAC Incirlik_Reaper",-1,{AUFTRAG.Type.ORBIT},100)

local e2Hawkers=SQUADRON:New("US_E2Hawkers", 8, "US_Hawkers") --Ops.Squadron#SQUADRON
e2Hawkers:SetCallsign(CALLSIGN.AWACS.Darkstar)
e2Hawkers:SetRadio(251.0)
e2Hawkers:SetSkill(AI.Skill.HIGH)
e2Hawkers:AddMissionCapability({AUFTRAG.Type.ORBIT},100)
e2Hawkers:SetFuelLowRefuel(true)
e2Hawkers:SetFuelLowThreshold(0.2)
e2Hawkers:SetTurnoverTime(10,20)
AWNavyBoys:AddSquadron(e2Hawkers)
AWNavyBoys:NewPayload("US_E2Hawkers",-1,{AUFTRAG.Type.ORBIT},100)

local recoveryTankers=SQUADRON:New("RecoveryTanker", 8, "recoveryTankers") --Ops.Squadron#SQUADRON
recoveryTankers:SetCallsign(CALLSIGN.Tanker.Shell)
recoveryTankers:SetRadio(251.0)
recoveryTankers:SetSkill(AI.Skill.HIGH)
recoveryTankers:AddMissionCapability({AUFTRAG.Type.RECOVERYTANKER, AUFTRAG.Type.TANKER},100)
recoveryTankers:SetFuelLowRefuel(true)
recoveryTankers:SetFuelLowThreshold(0.2)
recoveryTankers:SetTurnoverTime(10,20)
AWNavyBoys:AddSquadron(recoveryTankers)
AWNavyBoys:NewPayload("RecoveryTanker",-1,{AUFTRAG.Type.RECOVERYTANKER, AUFTRAG.Type.TANKER},100)

local boomTankers = SQUADRON:New("incirlik-aleppo-tanker", 8, "Incirlik-Tankers") --Ops.Squadron#SQUADRON
boomTankers:SetCallsign(CALLSIGN.Tanker.Arco)
boomTankers:SetRadio(141.0)
boomTankers:SetSkill(AI.Skill.HIGH)
boomTankers:AddMissionCapability({AUFTRAG.Type.TANKER},100)
boomTankers:SetFuelLowRefuel(true)
boomTankers:SetFuelLowThreshold(0.2)
boomTankers:SetTurnoverTime(10,20)
AWIncirlik:AddSquadron(boomTankers)
AWIncirlik:NewPayload("incirlik-aleppo-tanker",-1,{AUFTRAG.Type.TANKER},100)

local Squad_Two = SQUADRON:New("Escorts",12,"Escorts Navy")
Squad_Two:AddMissionCapability({AUFTRAG.Type.ESCORT})
Squad_Two:SetFuelLowRefuel(true)
Squad_Two:SetFuelLowThreshold(0.3)
Squad_Two:SetTurnoverTime(10,20)
Squad_Two:SetRadio(251,radio.modulation.AM)
AWNavyBoys:AddSquadron(Squad_Two)
AWNavyBoys:NewPayload("Escorts",-1,{AUFTRAG.Type.ESCORT},100)

local Squad_Incirlik_Escort = SQUADRON:New("Incirlik_Escorts",12,"Escorts Incirlik")
Squad_Incirlik_Escort:AddMissionCapability({AUFTRAG.Type.ESCORT})
Squad_Incirlik_Escort:SetFuelLowRefuel(true)
Squad_Incirlik_Escort:SetFuelLowThreshold(0.3)
Squad_Incirlik_Escort:SetTurnoverTime(10,20)
Squad_Incirlik_Escort:SetRadio(251,radio.modulation.AM)
AWIncirlik:AddSquadron(Squad_Incirlik_Escort)
AWIncirlik:NewPayload("Incirlik_Escorts",-1,{AUFTRAG.Type.ESCORT},100)

local Squad_Incirlik_AFAC = SQUADRON:New("AFAC Incirlik_Reaper",12,"Reaper Incirlik")
Squad_Incirlik_AFAC:AddMissionCapability({AUFTRAG.Type.ORBIT})
Squad_Incirlik_AFAC:SetRadio(254,radio.modulation.AM)
Squad_Incirlik_AFAC:SetTurnoverTime(10,20)
AWIncirlik:AddSquadron(Squad_Incirlik_AFAC)
AWIncirlik:NewPayload("Incirlik_Reaper",-1,{AUFTRAG.Type.ORBIT},100)

--local testawacs = AWACS:New("AWACS South",AWNavyBoys,"blue","GeorgeWashington","Awacs Orbit South",ZONE:FindByName("Rock"),"Fremont",251,radio.modulation.AM )
--testawacs:SetEscort(2)
--testawacs:SetAwacsDetails(CALLSIGN.AWACS.Focus,1,30,300,88,25)
--testawacs:SetModernEra()
--testawacs:__Start(5)

--local auftragRecoveryTanker = AUFTRAG:NewRECOVERYTANKER(UNIT:FindByName("GeorgeWashington"))
--auftragRecoveryTanker:SetRepeat(99)
--AWNavyBoys:AddMission(auftragRecoveryTanker)

--local ArcoLeg = ZONE:New("Arco-Leg")
-- Enable the tanker tasking for the north sector.
-- problem: Fuckton of SAMs are watching the area, you need to check all sites to reassure the zones are clear.
--local refuelArcoTask=AUFTRAG:NewTANKER(ArcoLeg:GetCoordinate(), 20000, 385, 70, 25)
--refuelArcoTask:SetTACAN(41, "ARC")
--refuelArcoTask:SetRadio(141)
--refuelArcoTask:SetRepeat(99)
--refuelArcoTask:SetRequiredEscorts(1, 2)
--AWIncirlik:AddMission(refuelArcoTask)
--