atisNalchik=ATIS:New(AIRBASE.Caucasus.Nalchik, 265.15)
atisNalchik:SetRadioRelayUnitName("ATIS Nalchik")
atisNalchik:SetTowerFrequencies({265.100, 165.100})
atisNalchik:SetImperialUnits()
atisNalchik:Start()