atisKhasabAB=ATIS:New(AIRBASE.PersianGulf.Khasab, 250.15)
atisKhasabAB:SetRadioRelayUnitName("ATIS KhasabAB")
atisKhasabAB:SetImperialUnits()
atisKhasabAB:SetTowerFrequencies({250.100, 150.100})
atisKhasabAB:Start()