atisLiwaAb=ATIS:New(AIRBASE.PersianGulf.Liwa_Airbase, 250.85)
atisLiwaAb:SetRadioRelayUnitName("ATIS LiwaAB")
atisLiwaAb:SetImperialUnits()
atisLiwaAb:SetTowerFrequencies({250.800, 119.325})
atisLiwaAb:Start()