atisAlDhafraAb=ATIS:New(AIRBASE.PersianGulf.Al_Dhafra_AB, 350.60)
atisAlDhafraAb:SetRadioRelayUnitName("ATIS AlDhafraAB")
atisAlDhafraAb:SetImperialUnits()
atisAlDhafraAb:SetActiveRunway("R")
atisAlDhafraAb:Start()