  -- RED UNITS
  autogft_Setup:new()
    :addBaseZone("Tblisi-Target-Airfield")
    :linkBase("Tblisi-Target-Airfield", "RU_tblisi_Airfield_Base")
    :startUsingRoads()
    :setSpeed(90)
    :addIntermidiateZone("Tblisi-Target-14")
    :addControlZone("Tblisi-Target-13")
    :addIntermidiateZone("Tblisi-Target-12")
    :addControlZone("Tblisi-Target-11")
    :addIntermidiateZone("Tblisi-Target-10")
    :addIntermidiateZone("Tblisi-Target-9")
    :addControlZone("Tblisi-Target-8")
    :addIntermidiateZone("Tblisi-Target-7")
    :addIntermidiateZone("Tblisi-Target-6")
    :addControlZone("Tblisi-Target-5")
    :addIntermidiateZone("Tblisi-Target-4")
    :addIntermidiateZone("Tblisi-Target-3")
    :addControlZone("Tblisi-Target-2")
    :addControlZone("Tblisi-Target-1")